
services:
  traccar-timeline:
    container_name: traccar-timeline
    image: ghcr.io/iamdabe/traccar-timeline:latest
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      # Nginx configuration
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - TRACCAR_API_URL=https://your-traccar-instance.com/api/
      - TRACCAR_USERNAME=your_username
      - TRACCAR_PASSWORD=your_password
